plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.145'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "${name}-${minecraft_version}"
}

// Mojang ships Java 21 to end users starting in 1.20.5, so mods should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

//minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')
//minecraft.accessTransformers.entry public net.minecraft.client.Minecraft textureManager # textureManager

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }

    gameTestServer {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenLocal()
    maven {
        name 'JEI'
        url 'https://maven.blamejared.com/'
        content {
            includeGroup 'mezz.jei'
        }
    }
    maven {
        name 'MineColonies'
        url 'https://ldtteam.jfrog.io/ldtteam/modding'
        content {
            includeGroup 'com.minecolonies'
            includeGroup 'com.ldtteam'
        }
    }
    maven {
        name 'CurseMaven'
        url 'https://www.cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven { url = 'https://maven.neoforged.net/releases' }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    compileOnly "curse.maven:jade-324717:${jade_file}"
    
    compileOnly "com.ldtteam:minecolonies:${colony_version}"
    compileOnly "com.ldtteam:structurize:${structurize_version}"
    compileOnly "com.ldtteam:domum-ornamentum:${domum_version}"
    compileOnly "com.ldtteam:blockui:${blockui_version}"

    if (project.include_jade.toBoolean()) {
        runtimeOnly "curse.maven:jade-324717:${jade_file}"
    }

    if (project.include_colony.toBoolean()) {
        runtimeOnly "com.ldtteam:minecolonies:${colony_version}"
        runtimeOnly "com.ldtteam:structurize:${structurize_version}"
        runtimeOnly "com.ldtteam:blockui:${blockui_version}"
        runtimeOnly "com.ldtteam:domum-ornamentum:${domum_version}"
        runtimeOnly "com.ldtteam:multipiston:${piston_version}"
    } else if (project.include_domum.toBoolean()) {
        runtimeOnly "com.ldtteam:domum-ornamentum:${domum_version}"
    }

    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    compileOnly 'com.intellij:annotations:+@jar'

    // implementation "blank:coolmod-${mc_version}:${coolmod_version}"
}

project.tasks.named("processResources") {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
            neo_version         : neo_version, neo_version_range: neo_version_range,
            loader_version_range: loader_version_range,
            mod_id              : mod_id,
            mod_name            : mod_name,
            mod_license         : mod_license,
            mod_version         : mod_version,
            mod_authors         : mod_authors,
            mod_description     : mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties + [project: project]
    }
}

jar.manifest.attributes([
    "Specification-Title"     : project.mod_id,
    "Specification-Vendor"    : project.mod_authors,
    "Specification-Version"   : "1",
    "Implementation-Title"    : project.name,
    "Implementation-Version"  : project.version,
    "Implementation-Vendor"   : project.mod_authors,
    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
])

java.withSourcesJar()

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId = project.base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
