# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.9
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=jadecolonies
mod_name=JadeColonies
mod_version=1.6.0
mod_license=GPLv3
mod_group_id=mirality
mod_authors=Mirality
mod_description=A Jade addon for MineColonies and/or Domum Ornamentum.
mod_issues=https://github.com/uecasm/jadecolonies/issues

include_jade=true
include_colony=true
include_domum=true

#Required mod dependencies
jade_mcversion=1.21.1
jade_version=15.3.4
jade_file=5706149

#Optional mod dependencies
colony_version=1.1.691-1.21.1-snapshot
structurize_version=1.0.751-1.21.1-snapshot
piston_version=1.2.50-1.21.1-snapshot
blockui_version=1.0.188-1.21.1-snapshot
domum_version=1.0.203-1.21.1-snapshot
datagen_version=1.20.4-0.1.57-ALPHA

jei_version=19.8.4.116
