# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
#org.gradle.jvmargs=
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.20.3
neogradle.subsystems.parchment.mappingsVersion=2023.12.31

# Environment Properties
minecraft_version=1.20.4
minecraft_version_range=[1.20.4,1.21)
neo_version=20.4.189
neo_version_range=[20.4,)
loader_version_range=[2,)

## Mod Properties
mod_id=jadecolonies
mod_name=JadeColonies
mod_version=1.5.0
mod_license=GPLv3
mod_group_id=mirality
mod_authors=Mirality
mod_description=A Jade addon for MineColonies and/or Domum Ornamentum.
mod_issues=https://github.com/uecasm/jadecolonies/issues

include_jade=true
include_colony=true
include_domum=true

#Required mod dependencies
jade_mcversion=1.20.4
jade_version=13.3.1
jade_file=5109393

#Optional mod dependencies
colony_version=1.20.4-1.1.532-BETA
structurize_version=1.20.4-1.0.717-BETA
piston_version=1.20.4-1.2.42-BETA
blockui_version=1.20.4-1.0.152-BETA
domum_version=1.20.4-1.0.179-BETA
datagen_version=1.20.4-0.1.57-ALPHA

jei_version=17.3.0.48
