modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${project.mod_issues}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/uecasm/jadecolonies/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jadecolonies"
logoFile="logo.png"
credits="Jade addon for MineColonies"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="jade"
    type="optional"
    versionRange="[${project.jade_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecolonies"
    type="optional"
    versionRange="[${project.colony_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="domum_ornamentum"
    type="optional"
    versionRange="[${project.domum_version},)"
    ordering="AFTER"
    side="BOTH"
